name: Hospital image build & scan Flow

on:
  push:
    branches:
      - deploying

concurrency:
  group: hospital-ci-${{ github.repository }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  sonar-scan:
    uses: ./.github/workflows/sonar-scan.yaml
    secrets: inherit

  dependency-scan:
    needs:
      - sonar-scan
    if: ${{ needs.sonar-scan.outputs.quality_gate_status == 'PASSED' }}
    uses: ./.github/workflows/snyk-scan.yaml
    secrets: inherit

  notify:
    needs:
      - sonar-scan
      - dependency-scan
    if: ${{ needs.sonar-scan.outputs.quality_gate_status == 'FAILED' || needs.dependency-scan.outputs.snyk_status == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Send Sonar notification
        if: ${{ needs.sonar-scan.outputs.quality_gate_status == 'FAILED' }}
        uses: ./.github/actions/send-notification
        with:
          pipeline_name: ${{ github.workflow }}
          repository_name: ${{ github.repository }}
          failure_reason: "SonarQube Quality Gate Failed"
          author: ${{ github.event.head_commit.author.name || github.actor }}
          smtp_username: ${{ secrets.SMTP_USERNAME }}
          smtp_password: ${{ secrets.SMTP_PASSWORD }}
          mail_from: ${{ secrets.MAIL_FROM }}
          mail_to: ${{ secrets.MAIL_TO }}
          slack_webhook: ${{ secrets.SLACK_INCOMING_WEBHOOK }}

      - name: Send Snyk notification
        if: ${{ needs.dependency-scan.outputs.snyk_status == 'failure' }}
        uses: ./.github/actions/send-notification
        with:
          pipeline_name: ${{ github.workflow }}
          repository_name: ${{ github.repository }}
          failure_reason: "Snyk Dependency Scan Failed"
          author: ${{ github.event.head_commit.author.name || github.actor }}
          smtp_username: ${{ secrets.SMTP_USERNAME }}
          smtp_password: ${{ secrets.SMTP_PASSWORD }}
          mail_from: ${{ secrets.MAIL_FROM }}
          mail_to: ${{ secrets.MAIL_TO }}
          slack_webhook: ${{ secrets.SLACK_INCOMING_WEBHOOK }}

  # image-build-scan:
  #   needs:
  #     - sonar-scan
  #     - dependency-scan
  #     - notify
  #   if: ${{ needs.sonar-scan.outputs.quality_gate_status == 'PASSED' && needs.dependency-scan.outputs.snyk_status == 'success' }}
  #   uses: ./.github/workflows/docker-scan.yaml
  #   secrets: inherit